# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/archlinux/gritty.png'

# Special
background='#0E0F11'
foreground='#85bbd7'
cursor='#85bbd7'

# Colors
color0='#0E0F11'
color1='#515452'
color2='#5F615E'
color3='#6C6E6B'
color4='#7E817E'
color5='#0B5AA1'
color6='#51738A'
color7='#85bbd7'
color8='#5d8296'
color9='#515452'
color10='#5F615E'
color11='#6C6E6B'
color12='#7E817E'
color13='#0B5AA1'
color14='#51738A'
color15='#85bbd7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
