--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/backgrounds/archlinux/gritty.png"

-- Special
background="#0E0F11"
foreground="#85bbd7"
cursor="#85bbd7"

-- Colors
color0="#0E0F11"
color1="#515452"
color2="#5F615E"
color3="#6C6E6B"
color4="#7E817E"
color5="#0B5AA1"
color6="#51738A"
color7="#85bbd7"
color8="#5d8296"
color9="#515452"
color10="#5F615E"
color11="#6C6E6B"
color12="#7E817E"
color13="#0B5AA1"
color14="#51738A"
color15="#85bbd7"
